# Generated by Django 2.2.6 on 2019-12-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='photos/%y/%m/%d', verbose_name='画像'),
        ),
    ]
