# Generated by Django 2.2.6 on 2020-02-07 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='multi_images',
            field=models.FileField(blank=True, null=True, upload_to='multi_photos', verbose_name='画像'),
        ),
    ]
