# Generated by Django 2.2.6 on 2020-01-04 02:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schedule_date', models.DateField(verbose_name='Date')),
                ('summary', models.CharField(max_length=50, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Text')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
            ],
        ),
    ]
