# Generated by Django 2.2.6 on 2020-01-04 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='schedule_date',
            new_name='date',
        ),
    ]
